"""SFT training script for Qwen3.5-4B on Eden distillation data.

Trains a Qwen3.5-4B-Instruct model on RAG distillation data generated by
``generate_rag_distillation.py``.  Uses TRL ``SFTTrainer`` and PyTorch FSDP
via ``accelerate`` for multi-GPU training on 4x H100 nodes.

References:
    TRL SFTTrainer docs: https://huggingface.co/docs/trl/sft_trainer
    Accelerate FSDP docs: https://huggingface.co/docs/accelerate/usage_guides/fsdp

Launch (single node, 4x H100)::

    accelerate launch --config_file training/fsdp_config.yaml \\
        --num_processes 4 training/sft_train.py \\
        --config training/sft_config.yaml

Dry-run on 1 GPU::

    accelerate launch --num_processes 1 training/sft_train.py \\
        --config training/sft_config.yaml --max-steps 5

The ``--config`` argument is the only required flag; all other values come
from the YAML and can be overridden on the command line.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Annotated

import typer
import yaml
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import SFTConfig, SFTTrainer

from training.data_prep import build_dataset

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Config loading
# ---------------------------------------------------------------------------


def load_config(path: Path) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------


def train(
    config_path: Path,
    max_steps: int | None = None,
) -> None:
    """Run SFT training.

    Parameters
    ----------
    config_path:
        Path to ``sft_config.yaml``.
    max_steps:
        Override ``max_steps`` for quick smoke-tests (``None`` uses epochs).
    """
    cfg = load_config(config_path)

    model_name: str = cfg["model_name"]
    data_paths = [Path(p) for p in cfg["data_paths"]]
    output_dir: str = cfg["output_dir"]
    max_seq_length: int = cfg.get("max_seq_length", 4096)
    eval_split: float = cfg.get("eval_split", 0.05)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )

    # ------------------------------------------------------------------
    # Model + tokeniser
    # ------------------------------------------------------------------
    logger.info("Loading tokeniser: %s", model_name)
    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    logger.info("Loading model: %s", model_name)
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        trust_remote_code=True,
        use_cache=False,  # required with gradient checkpointing
    )

    # ------------------------------------------------------------------
    # Dataset
    # ------------------------------------------------------------------
    logger.info("Building dataset from %d file(s)", len(data_paths))
    train_dataset, eval_dataset = build_dataset(
        data_paths=data_paths,
        tokenizer=tokenizer,
        max_seq_length=max_seq_length,
        eval_split=eval_split,
    )
    logger.info(
        "Train: %d examples  Eval: %d examples",
        len(train_dataset),
        len(eval_dataset),
    )

    # ------------------------------------------------------------------
    # SFT config
    # ------------------------------------------------------------------
    sft_cfg = SFTConfig(
        output_dir=output_dir,
        # Training schedule
        num_train_epochs=cfg.get("num_train_epochs", 3),
        max_steps=max_steps if max_steps is not None else -1,
        # Batch sizes — effective batch = per_device * grad_accum * num_gpus
        per_device_train_batch_size=cfg.get("per_device_train_batch_size", 4),
        per_device_eval_batch_size=cfg.get("per_device_eval_batch_size", 4),
        gradient_accumulation_steps=cfg.get("gradient_accumulation_steps", 4),
        # Optimisation
        learning_rate=cfg.get("learning_rate", 1e-5),
        lr_scheduler_type=cfg.get("lr_scheduler_type", "cosine"),
        warmup_ratio=cfg.get("warmup_ratio", 0.05),
        weight_decay=cfg.get("weight_decay", 0.01),
        # Mixed precision + memory
        bf16=cfg.get("bf16", True),
        gradient_checkpointing=cfg.get("gradient_checkpointing", True),
        # Sequence packing for efficiency
        packing=cfg.get("packing", True),
        max_seq_length=max_seq_length,
        dataset_text_field="text",
        # Logging + checkpointing
        logging_steps=cfg.get("logging_steps", 10),
        save_steps=cfg.get("save_steps", 500),
        eval_strategy="steps",
        eval_steps=cfg.get("eval_steps", cfg.get("save_steps", 500)),
        save_total_limit=cfg.get("save_total_limit", 3),
        load_best_model_at_end=cfg.get("load_best_model_at_end", True),
        metric_for_best_model="eval_loss",
        greater_is_better=False,
        # Reporting
        report_to=cfg.get("report_to", "none"),
        run_name=cfg.get("run_name", "eden-sft"),
        # FSDP sets up sharding via accelerate config; no extra flags needed here.
        fsdp=cfg.get("fsdp", ""),
        fsdp_config=cfg.get("fsdp_config", {}),
    )

    # ------------------------------------------------------------------
    # Trainer
    # ------------------------------------------------------------------
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        args=sft_cfg,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
    )

    logger.info("Starting training")
    trainer.train()
    trainer.save_model(output_dir)
    tokenizer.save_pretrained(output_dir)
    logger.info("Model saved to %s", output_dir)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

app = typer.Typer()


@app.command()
def main(
    config: Annotated[Path, typer.Option(help="Path to sft_config.yaml")] = Path(
        "training/sft_config.yaml"
    ),
    max_steps: Annotated[
        int | None,
        typer.Option(help="Override max training steps (for smoke-tests)"),
    ] = None,
) -> None:
    """Fine-tune Qwen3.5-4B on Eden RAG distillation data."""
    train(config_path=config, max_steps=max_steps)


if __name__ == "__main__":
    app()
